pipeline.py

Add value to location dict: 'rarely_left_the_house_but_visited_lots'

---

.readthedocs.yaml
README.md
docs/Makefile
docs/conf.py
docs/index.rst
docs/requirements.txt

This should add what's needed to start automatic documentation with ReadTheDocs. Fixes #101 .

Adding RTFD Documentation Stuff

---

exetera/core/data_schema.py
exetera/core/load_schema.py
exetera/core/readerwriter.py
tests/test_importer.py
tests/test_persistence.py

importer: add default value to numeric fields

---

exetera/core/data_schema.py
exetera/core/load_schema.py
exetera/core/readerwriter.py
tests/test_importer.py
tests/test_persistence.py

expand importer option: validation/flag

---

exetera/core/data_schema.py
exetera/core/load_schema.py
exetera/core/readerwriter.py
tests/test_importer.py

import datetime/date: create_day_field

---

exetera/core/utils.py
exetera/processing/date_time_helpers.py
tests/test_date_time_helpers.py

Redoing the pull request because git got itself very wound up

Adding functionality for time-period-based stratification

---

exetera/core/abstract_types.py
exetera/core/dataframe.py
exetera/core/dataset.py
exetera/core/fields.py
exetera/core/session.py
tests/test_dataframe.py
tests/test_dataset.py
tests/test_fields.py
tests/test_session.py

Work still to do:
* Tests for is_sorted
* is_sorted added to abstract Field once that it goes through

Initial commit for is_sorted method on Field

---

exetera/core/fields.py
exetera/core/session.py
tests/test_session.py

Caused during merging of conflicting session PRS

Support direct use of h5py groups

---

exetera/processing/date_time_helpers.py
tests/test_date_time_helpers.py

WIP to make the API easier to use

Test to support out of range days for get_period_offsets

---

docs/conf.py
docs/exetera.core.rst
docs/exetera.processing.rst
docs/index.rst
exetera/bin/exetera_perf_tests.py
exetera/bin/journal_test.py
exetera/core/dataframe.py
exetera/core/dataset.py
exetera/core/fields.py
exetera/core/readerwriter.py
exetera/core/session.py
exetera/processing/__init__.py
exetera/processing/date_time_helpers.py

Closes #174 #121 
This reformats the docstrings that exist into the correct format for Sphinx. A few other changes and fixes were done where appropriate in relation to getting this working correctly.

Update of docstring formatting

---

exetera/core/field_importers.py
exetera/io/parsers.py
tests/test_parsers.py

schema missing fields would be treated as IndexedStringField

---

exetera/core/dataframe.py
exetera/core/fields.py
exetera/core/validation.py
tests/test_dataframe.py

to_csv() api using csv.writer

---

exetera/core/field_importers.py
exetera/io/load_schema.py
tests/test_importer.py
tests/test_parsers.py
tests/test_session.py

DateImporter return timestamp, also add create_day_flag

---

.github/workflows/python-app.yml
README.md

This adds Codecov support in the testing workflow.

Adding Codecov

---

.github/workflows/python-app.yml

Signed-off-by: Eric Kerfoot <eric.kerfoot@kcl.ac.uk>

Fix for Windows tests

---

exetera/core/abstract_types.py
exetera/core/fields.py
exetera/core/operations.py
tests/test_fields.py

implement field.unique

---

requirements.txt

Signed-off-by: Eric Kerfoot <eric.kerfoot@kcl.ac.uk>

Numba version fix

---

.github/workflows/python-app.yml
exetera/__init__.py
setup.py

Adds a call to the `exetera` executable entry point to make sure it actually works.

Pip Install Added Check

---

exetera/bin/exetera
exetera/io/importer.py
tests/test_importer.py

A fix to the import functionality re-enabling the ability to import multiple csvs into the same import

urgent commit to fix broken import on master

---

exetera/core/fields.py
tests/test_fields.py

fix create_like for IndexedStringMemField

---

docs/requirements.txt

Jinja2 made some changes that broke compatibility with Sphinx, pinning the version for now.

Fix for breaking change in Jinja2

---

exetera/core/operations.py
tests/test_fields.py

isin unittest with parameterized
